### ISSUE TITLE
Issue: Adjusting time in SpurWeb Confusion Ticket 33038

### ISSUE THREAD

**Issue by dwd0005** [spurjobs/spur-website#3]
@WillOgles commented on [Tue Sep 18 2018](https://github.com/spurjobs/Agile-Core-Interaction/issues/3665)

This Github issue is synchronized with Zendesk:

**Ticket ID:** [#33038](https://spur.zendesk.com/agent/tickets/33038)
**Group:** Support
**Requester:** joy@spurjobs.com
**Assignee:** Spur Support
**Issue escalated by:** Spur Support

**Original ticket description:**

<blockquote><div class="zd-comment zd-comment-pre-styled"><div dir="ltr">
<div dir="ltr">When you adjust someone's time, it asks for Start time, End time and then you add break out and in. If you submit it this way the results come back as Start time, break out, break in, end time. I believe the field labels just need to be updated to reflect the proper order. That may explain why we find so many with punches out of order.<br>
</div>
<div dir="ltr"><br></div>
<div>If you have an inactive worker, you can try to record this. I didn't want to adjust time and confuse the worker. If I have to make another adjustment today, I will send a video of the issue. </div>
<img src="http://t.sidekickopen13.com/e1t/o/5/f18dQhb0S7kC8dDMPbW2n0x6l2B9gXrN7sKj6v5KRN6N56jT_WQsN5HVd3_yK80-y-Kf197v5Y04?si=7000000001880940&amp;pi=c648926a-295a-4caf-e0ad-760425c0142b&amp;ti=null" style="display: none !important" height="1" width="1">
</div></div></blockquote>

---

@SamWear commented on [Wed Sep 19 2018](https://github.com/spurjobs/Agile-Core-Interaction/issues/3665#issuecomment-422840029)

Are we talking about when someone's time is adjusted in Spur Web? Or the admin tools? I'm a little confused what is being asked and what the repro steps are exactly.

**Comment by dwd0005** [comment]
I believe this is a Spur Website issue. If not, feel free to bounce back over, Chris.

**Comment by cmhand** [comment]
Issue moved to [spurjobs/spur-ent #2260](https://github.com/spurjobs/spur-ent/issues/2260) via [**ZenHub**](https://www.zenhub.com/)
